version: '3.9'
services:
  web:
    build: .
    container_name: myapp
    ports:
      - '7777:80'
    volumes:
      - ./src:/usr/share/nginx/src
      - ./public:/usr/share/nginx/html/
    depends_on:
      - db
    networks:
      - myapp-net
  db:
    image: mysql:latest
    container_name: myapp-db
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: myrootpass
    networks:
      - myapp-net
networks:
  myapp-net: